### ISSUE TITLE
When visualizing with own images: ValueError: cannot reshape array of size 5 into shape (2,2)

### ISSUE THREAD

**Issue by BennoStaub** [waspinator/pycococreator#2]
Hey, I recreated the steps with my own image as attached. Adapting your shapes_to_coco.py script by changing class names it worked. However, in the last step of visualizing them with your jupyter notebook (there is an error, the annotation_file is not in the annotations dir but in the train dir) I get the following error: ValueError: cannot reshape array of size 5 into shape (2,2). Screenshot is attached too.
![screenshot from 2018-04-18 15-11-08](https://user-images.githubusercontent.com/22842744/38934099-24fe4cf2-431b-11e8-975d-93252178fc76.png)

![1_cube_3](https://user-images.githubusercontent.com/22842744/38933832-63175872-431a-11e8-9a8c-9d7e1bd2cab6.png)
![1_cuboid_2](https://user-images.githubusercontent.com/22842744/38933833-6331728e-431a-11e8-97b1-2bac2ffbc218.png)
![1_triangle_1](https://user-images.githubusercontent.com/22842744/38933834-634c0b3a-431a-11e8-860e-c72b92beab30.png)
![1](https://user-images.githubusercontent.com/22842744/38933841-67ab4ad8-431a-11e8-912a-870ec626e289.jpg)

Maybe we can discuss this in detail via mail to speed up fixing it: staubbe@student.ethz.ch

**Comment by waspinator** [comment]
Thanks for reporting the issue. This is a bug in when when contours have fewer than three points. I'll push a fix soon.

**Comment by waspinator** [comment]
Try installing pycococreatortools from master and rerunning your script. The notebook should work now.
