### ISSUE TITLE
TypeError: Argument 'bb' has incorrect type (expected numpy.ndarray, got list)

### ISSUE THREAD

**Issue by austinmw** [waspinator/pycococreator#4]
I'm getting this while trying to train the matterport mask rcnn model on my own data created with this tool. Anybody know what this is caused by? Another person opened this issue here: https://github.com/cocodataset/cocoapi/issues/139 but closed it without saying how to fix.

**Comment by waspinator** [comment]
If you weren't using the master branch, try updating to 0.1.5, and rerunning it on your dataset. I think that may fix your issue.

https://github.com/waspinator/pycococreator/releases/

**Comment by austinmw** [comment]
Okay thanks, going to try 0.1.5 now

**Comment by austinmw** [comment]
Looks like that error is gone, thanks!! However, I'm now getting a new error, but this one thankfully doesn't crash training. I'm not sure if it's because of the way the data was generated, config settings, or pycocotools api to be honest, but I'm going to create a new issue for it.
