### ISSUE TITLE
Question: overlapping annotations?

### ISSUE THREAD

**Issue by austinmw** [waspinator/pycococreator#6]
Does this happen to support overlapping masks? For example 'car' and 'tire'. Also I can see how that would be represented as different objects in an XML file, but how would that be represented in a jpeg mask? Thanks!

I see that there's the parameter `is_crowd`, but not sure how that may be determined from a jpeg mask.

**Comment by waspinator** [comment]
Yes, you could have overlapping masks represented by the COCO format. To use the example code which converts binary masks you would have a binary mask in a file named `<image_id>_<class_name_one>.png`, and then a mask which overlaps the first one named`<image_id>_<class_name_two>.png`. In the example the `is_crowd` property is also only encoded in the file name. Ex: `<image_id>_<class_name_two>_crowd`.png`
