### ISSUE TITLE
The installed module is not found in Jupyter Notebook

### ISSUE THREAD

**Issue by StringBottle** [waspinator/pycococreator#7]
Thanks for sharing your library. 
But your module 'pycocotools' is not found in your Jupyter Notebook example 'visualize_coco'. 
after installation. 
I can find a library named 'pycococreatortools' by library searching using 'pip list' command 
but not pycocotools.

Is there any specific requirement for your library? 
I currently use Anaconda 3 environment and I installed it using Anaconda Prompt. 
+ I am completely new to python language.

**Comment by waspinator** [comment]
Try installing from here:

https://github.com/waspinator/coco#install

**Comment by afunTW** [comment]
I got the same issue and found here, would it be better to add the pycocotools as this dependencies?
that will be better than install this package and check the pycocotools after that

**Comment by waspinator** [comment]
the pycocotools in pip had issues with python3 when I last tried them. I added instructions on installing a branch of pycocotools with python3 support in the README. I haven't found a good way of adding a git repo as a dependency in a setup.py file. 

I'll test some of the solutions explained here when I get a chance.

- https://stackoverflow.com/questions/18026980/python-setuptools-how-can-i-list-a-private-repository-under-install-requires
